# Generated by Django 3.2 on 2021-04-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInformation',
        ),
    ]
