# Generated by Django 3.2 on 2021-05-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210501_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='BlogUser',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
