# Generated by Django 3.2.2 on 2021-05-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
